### ISSUE TITLE
How to generate new challenge datasets for other NLI datasets?

### ISSUE THREAD

**Issue by abhilashreddys** [ohadrozen/inferbert#1]
How to generate the jsons in the dataset folder?

**Comment by ohadrozen** [comment]
Thanks for your interest in our work.
Our datasets were generated manually using Mechanical Turk (you can read about the process in our [paper](https://aclanthology.org/2021.starsem-1.8.pdf) on Section 3.2).
You should simply download them from here: https://github.com/ohadrozen/inferbert/tree/main/datasets

**Comment by abhilashreddys** [comment]
My bad, I should have rephrased my question. Anyways reading the paper again solved the query.
Thanks.

**Comment by ohadrozen** [comment]
no worries. happy to hear it is solved. Please let me know should you have any more questions.
